#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # store variables
    path_to_file="$1"
    ip="$2"
    username="$3"
    path_to_ssh_key="$4"

    # securely transfer file to remote host 
    scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~/
fi
